# Homework for Week 3

The goal for this homework is to see the relevant journalistic uses for what we learned in class in week 2.

1. access specific data within a dataset,
2. break down larger datasets into smaller chunks (subset),
3. Ingest different types of spreadsheets into Pandas,
4. Gather general info about our dataframes

# List Slicing
## Natural disasters list

The Small Business Administration has a list of natural disasters that cause extensive economic damage. Run the next cell to pull the list into memory

In [1]:
disasters = [
        "Landslides",
        "Earthquake",
        "Wildfires",
        "Tornadoes",
        "Hurricane",
        "Wind Storm",
        "Winter Freeze",
        "Ice Storm",
        "Drought",
        "Tsunami",
        "Flash floods",
        "Mudslides",
        "Torrential rainfall",
        "Riverine floods",
        "Tidal Surge"
         ]

In [2]:
## call the disaster list here
disasters

['Landslides',
 'Earthquake',
 'Wildfires',
 'Tornadoes',
 'Hurricane',
 'Wind Storm',
 'Winter Freeze',
 'Ice Storm',
 'Drought',
 'Tsunami',
 'Flash floods',
 'Mudslides',
 'Torrential rainfall',
 'Riverine floods',
 'Tidal Surge']

In [7]:
## the first item in the list
disasters[1]

'Earthquake'

In [8]:
## call the penultimate item (without manually counting the number of items)
disasters[-2]

'Riverine floods'

### Clarification:

For the next two questions, I am referring to numerical positions rather than zero-indexed positions. In other words, you will have to translate the numerical position into zero-indexed positions in your slicing.

In [17]:
## create a new list called disasters_subset that holds the 3rd to 6th items inclusive
disasters_subset= disasters[:6]
disasters_subset

['Landslides',
 'Earthquake',
 'Wildfires',
 'Tornadoes',
 'Hurricane',
 'Wind Storm']

In [22]:
## create a new list called disasters_subset2 that holds the 2nd through 8th items
disasters_subset2 = disasters[2:9]
disasters_subset2

['Wildfires',
 'Tornadoes',
 'Hurricane',
 'Wind Storm',
 'Winter Freeze',
 'Ice Storm',
 'Drought']

## Pandas - Importing data

Please download from Google Drive the following data and then upload it into this notebook:

- <a href="https://drive.google.com/file/d/1izg0nXFm8vBJAhz77LFdSMQGP4STvpEk/view?usp=sharing">EMS excerpt</a>,

- <a href="https://docs.google.com/spreadsheets/d/1sUEttreon8IKzCmsfRQ6cPA1lfeuNDu9/edit?usp=sharing&ouid=107646296031550187966&rtpof=true&sd=true">Customs, Border Patrol</a>

**Give yourself time to download it. Some of the files are large!**

In [4]:
## import the pandas library in this cell
import pandas as pd

### Ingest the following dataset into this note:

- ```ems20_1st_6months_excerpt.csv``` into a dataframe named ```ems2020_excerpt_df```

In [5]:
## import data and store in dataframe
ems2020_excerpt_df=pd.read_csv("ems20_1st_6months_excerpt.csv")
ems2020_excerpt_df

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201101264,2020-04-19 10:25:47,INJMIN,7,INJMIN,7,04/19/2020 10:26:24 AM,Y,37,04/19/2020 10:26:24 AM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk170.csv
1,200423766,2020-02-11 19:25:47,CARD,3,SICK,6,02/11/2020 07:25:56 PM,Y,9,02/11/2020 07:26:09 PM,...,52.0,14.0,207.0,10.0,15.0,N,N,N,N,chunk166.csv
2,200434110,2020-02-12 21:36:52,UNC,2,UNC,2,02/12/2020 09:37:24 PM,Y,32,02/12/2020 09:38:27 PM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk166.csv
3,201610121,2020-06-09 00:52:30,DRUG,4,DRUG,4,06/09/2020 12:52:44 AM,Y,14,06/09/2020 12:52:59 AM,...,19.0,4.0,108.0,2.0,12.0,N,N,N,N,chunk171.csv
4,200034112,2020-01-03 20:44:05,DRUG,4,DRUG,4,01/03/2020 08:44:11 PM,Y,6,01/03/2020 08:44:17 PM,...,66.0,39.0,312.0,15.0,7.0,N,N,N,N,chunk165.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13112,200393407,2020-02-08 19:49:33,DIFFBR,2,DIFFBR,2,02/08/2020 07:52:34 PM,Y,181,02/08/2020 07:53:00 PM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk166.csv
13113,200034618,2020-01-03 22:51:33,INJURY,5,INJURY,5,01/03/2020 10:51:39 PM,Y,6,01/03/2020 10:52:21 PM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk165.csv
13114,200424355,2020-02-11 21:51:09,SICK,6,SICK,6,02/11/2020 09:52:09 PM,Y,60,02/11/2020 09:52:18 PM,...,48.0,15.0,206.0,10.0,15.0,N,N,N,N,chunk166.csv
13115,201742708,2020-06-22 15:57:44,MVAINJ,4,MVAINJ,4,06/22/2020 03:58:07 PM,Y,23,06/22/2020 03:58:19 PM,...,62.0,47.0,311.0,21.0,11.0,N,N,N,N,chunk172.csv
13116,200865674,2020-03-26 19:33:19,DIFFFC,2,DIFFFC,2,03/26/2020 07:33:50 PM,Y,31,03/26/2020 07:34:08 PM,...,103.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk168.csv

In [13]:
## call the first 10 rows
ems2020_excerpt_df.head (10)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201101264,2020-04-19 10:25:47,INJMIN,7,INJMIN,7,04/19/2020 10:26:24 AM,Y,37,04/19/2020 10:26:24 AM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk170.csv
1,200423766,2020-02-11 19:25:47,CARD,3,SICK,6,02/11/2020 07:25:56 PM,Y,9,02/11/2020 07:26:09 PM,...,52.0,14.0,207.0,10.0,15.0,N,N,N,N,chunk166.csv
2,200434110,2020-02-12 21:36:52,UNC,2,UNC,2,02/12/2020 09:37:24 PM,Y,32,02/12/2020 09:38:27 PM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk166.csv
3,201610121,2020-06-09 00:52:30,DRUG,4,DRUG,4,06/09/2020 12:52:44 AM,Y,14,06/09/2020 12:52:59 AM,...,19.0,4.0,108.0,2.0,12.0,N,N,N,N,chunk171.csv
4,200034112,2020-01-03 20:44:05,DRUG,4,DRUG,4,01/03/2020 08:44:11 PM,Y,6,01/03/2020 08:44:17 PM,...,66.0,39.0,312.0,15.0,7.0,N,N,N,N,chunk165.csv
5,200530247,2020-02-22 01:26:18,DRUG,4,DRUG,4,02/22/2020 01:27:21 AM,Y,63,02/22/2020 01:27:41 AM,...,25.0,8.0,111.0,4.0,12.0,N,N,N,N,chunk167.csv
6,200543279,2020-02-23 19:08:27,UNC,2,UNC,2,02/23/2020 07:08:44 PM,Y,17,02/23/2020 07:09:16 PM,...,44.0,8.0,204.0,9.0,15.0,N,N,N,N,chunk167.csv
7,201471743,2020-05-26 12:45:46,INJURY,5,INJURY,5,05/26/2020 12:46:04 PM,Y,18,05/26/2020 12:46:15 PM,...,41.0,17.0,202.0,8.0,15.0,N,N,N,N,chunk171.csv
8,201180116,2020-04-27 00:57:48,EDP,7,EDPC,7,04/27/2020 12:58:07 AM,Y,19,04/27/2020 12:58:15 AM,...,50.0,11.0,208.0,10.0,16.0,N,N,N,N,chunk170.csv
9,200572739,2020-02-26 15:15:25,CARDBR,2,CARDBR,2,02/26/2020 03:16:35 PM,Y,70,02/26/2020 03:16:49 PM,...,106.0,28.0,410.0,27.0,5.0,N,N,N,N,chunk167.csv

In [11]:
## call the last 5 rows
ems2020_excerpt_df.tail(5)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
13112,200393407,2020-02-08 19:49:33,DIFFBR,2,DIFFBR,2,02/08/2020 07:52:34 PM,Y,181,02/08/2020 07:53:00 PM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk166.csv
13113,200034618,2020-01-03 22:51:33,INJURY,5,INJURY,5,01/03/2020 10:51:39 PM,Y,6,01/03/2020 10:52:21 PM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk165.csv
13114,200424355,2020-02-11 21:51:09,SICK,6,SICK,6,02/11/2020 09:52:09 PM,Y,60,02/11/2020 09:52:18 PM,...,48.0,15.0,206.0,10.0,15.0,N,N,N,N,chunk166.csv
13115,201742708,2020-06-22 15:57:44,MVAINJ,4,MVAINJ,4,06/22/2020 03:58:07 PM,Y,23,06/22/2020 03:58:19 PM,...,62.0,47.0,311.0,21.0,11.0,N,N,N,N,chunk172.csv
13116,200865674,2020-03-26 19:33:19,DIFFFC,2,DIFFFC,2,03/26/2020 07:33:50 PM,Y,31,03/26/2020 07:34:08 PM,...,103.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk168.csv

In [12]:
## call a 20 random rows
ems2020_excerpt_df.sample(20)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
3891,201402546,2020-05-19 17:25:10,INJURY,4,INJURY,4,05/19/2020 05:26:02 PM,Y,52,05/19/2020 05:26:49 PM,...,47.0,11.0,212.0,11.0,16.0,N,N,N,N,chunk171.csv
7360,201650092,2020-06-13 00:29:11,DIFFBR,2,DIFFBR,2,06/13/2020 12:29:24 AM,Y,13,06/13/2020 12:29:34 AM,...,62.0,44.0,311.0,20.0,10.0,N,N,N,N,chunk171.csv
9295,200370248,2020-02-06 01:41:22,INJURY,5,INJURY,5,02/06/2020 01:41:30 AM,Y,8,02/06/2020 01:41:49 AM,...,121.0,49.0,501.0,31.0,11.0,N,N,N,N,chunk166.csv
6105,200591664,2020-02-28 11:35:48,SICK,6,SICK,6,02/28/2020 11:36:05 AM,Y,17,02/28/2020 11:36:18 AM,...,33.0,10.0,112.0,6.0,13.0,N,N,N,N,chunk167.csv
12108,201402125,2020-05-19 15:08:35,UNKNOW,4,UNKNOW,4,05/19/2020 03:08:47 PM,Y,12,05/19/2020 03:09:26 PM,...,49.0,13.0,211.0,11.0,14.0,N,N,N,N,chunk171.csv
12013,200642581,2020-03-04 14:58:48,SICK,6,CARD,3,03/04/2020 02:59:02 PM,Y,14,03/04/2020 02:59:09 PM,...,78.0,35.0,306.0,13.0,9.0,N,N,N,N,chunk167.csv
95,200121397,2020-01-12 09:20:46,UNC,2,UNC,2,01/12/2020 09:21:22 AM,Y,36,01/12/2020 09:21:30 AM,...,48.0,15.0,206.0,10.0,15.0,N,N,N,N,chunk165.csv
3172,201151266,2020-04-24 10:32:53,STATEP,2,STATEP,2,04/24/2020 10:33:20 AM,Y,27,04/24/2020 10:33:33 AM,...,23.0,9.0,111.0,4.0,13.0,N,N,N,N,chunk170.csv
12705,200393693,2020-02-08 20:58:09,INJURY,5,INJURY,5,02/08/2020 08:58:35 PM,Y,26,02/08/2020 08:58:42 PM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk166.csv
4167,201241577,2020-05-03 12:36:43,INJURY,5,INJURY,5,05/03/2020 12:36:55 PM,Y,12,05/03/2020 12:37:15 PM,...,102.0,28.0,409.0,27.0,5.0,N,N,N,N,chunk170.csv
5980,201730346,2020-06-21 01:49:17,EDP,7,EDPC,7,06/21/2020 02:00:39 AM,Y,682,06/21/2020 02:01:44 AM,...,47.0,11.0,212.0,11.0,16.0,N,N,N,N,chunk172.csv
12099,201072270,2020-04-16 14:11:54,DIFFFC,2,DIFFFC,2,04/16/2020 02:12:11 PM,Y,17,04/16/2020 02:12:22 PM,...,106.0,28.0,410.0,27.0,5.0,N,N,N,N,chunk169.csv
11641,200871339,2020-03-27 07:32:05,EDP,7,CVAC,2,03/27/2020 08:08:00 AM,Y,2155,03/27/2020 08:10:07 AM,...,47.0,12.0,212.0,11.0,16.0,N,N,N,N,chunk168.csv
9305,200884223,2020-03-28 16:37:40,UNC,2,UNC,2,03/28/2020 04:38:13 PM,Y,33,03/28/2020 04:38:27 PM,...,67.0,45.0,317.0,18.0,9.0,N,N,N,N,chunk168.csv
11176,201580929,2020-06-06 09:15:12,INJURY,5,INJURY,5,06/06/2020 09:15:33 AM,Y,21,06/06/2020 09:15:46 AM,...,14.0,3.0,104.0,2.0,10.0,N,N,N,N,chunk171.csv
1796,201821986,2020-06-30 13:34:06,CARDBR,2,CARDBR,2,06/30/2020 01:34:16 PM,Y,10,06/30/2020 01:34:27 PM,...,7.0,1.0,103.0,1.0,7.0,N,N,N,N,chunk172.csv
8449,200111341,2020-01-11 09:12:40,CARD,3,SICK,6,01/11/2020 09:12:53 AM,Y,13,01/11/2020 09:13:05 AM,...,34.0,10.0,112.0,6.0,13.0,N,N,N,N,chunk165.csv
10061,201211271,2020-04-30 11:25:04,OBLAB,5,OBLAB,5,04/30/2020 11:25:11 AM,Y,7,04/30/2020 11:25:28 AM,...,44.0,16.0,204.0,9.0,15.0,N,N,N,N,chunk170.csv
6536,201662544,2020-06-14 17:35:35,CARDBR,2,CARDBR,2,06/14/2020 05:35:53 PM,Y,18,06/14/2020 05:36:20 PM,...,105.0,23.0,413.0,26.0,3.0,N,N,N,N,chunk171.csv
3353,201572126,2020-06-05 14:27:14,EDP,7,EDP,7,06/05/2020 02:27:30 PM,Y,16,06/05/2020 02:27:56 PM,...,76.0,39.0,306.0,15.0,7.0,N,N,N,N,chunk171.csv

In [18]:
## how might you slice this df to show only rows 42 through 51 inclusive
ems2020_excerpt_df.iloc[42:52]

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
42,201542166,2020-06-02 14:39:16,CVAC,2,CVAC,2,06/02/2020 02:39:24 PM,Y,8,06/02/2020 02:39:43 PM,...,88.0,35.0,302.0,13.0,8.0,N,N,N,N,chunk171.csv
43,201290003,2020-05-08 00:02:09,EDP,7,EDP,7,05/08/2020 12:02:34 AM,Y,25,05/08/2020 12:02:55 AM,...,23.0,8.0,111.0,4.0,13.0,N,N,N,N,chunk170.csv
44,201034249,2020-04-12 21:17:40,SICK,6,SICK,6,04/12/2020 09:20:33 PM,Y,173,04/12/2020 09:20:33 PM,...,75.0,37.0,305.0,19.0,8.0,N,N,N,N,chunk169.csv
45,201784219,2020-06-26 22:59:45,INJURY,5,INJURY,5,06/26/2020 10:59:54 PM,Y,9,06/26/2020 11:00:01 PM,...,114.0,22.0,401.0,30.0,12.0,N,N,N,N,chunk172.csv
46,201001249,2020-04-09 08:29:26,INJURY,5,INJURY,5,04/09/2020 08:29:30 AM,Y,4,04/09/2020 08:29:55 AM,...,122.0,50.0,502.0,31.0,11.0,N,N,N,N,chunk169.csv
47,200880324,2020-03-28 01:22:22,SICK,6,SICK,6,03/28/2020 01:23:56 AM,Y,94,03/28/2020 01:24:07 AM,...,5.0,1.0,101.0,2.0,7.0,N,N,N,N,chunk168.csv
48,201323660,2020-05-11 23:40:32,UNC,2,UNC,2,05/11/2020 11:40:43 PM,Y,11,05/11/2020 11:40:48 PM,...,40.0,8.0,201.0,7.0,15.0,Y,N,N,N,chunk170.csv
49,201632450,2020-06-11 16:18:15,TRAUMA,2,TRAUMA,2,06/11/2020 04:18:34 PM,Y,19,06/11/2020 04:19:07 PM,...,67.0,40.0,317.0,17.0,9.0,N,N,N,N,chunk171.csv
50,200630307,2020-03-03 02:35:05,SICK,6,SICK,6,03/03/2020 02:35:16 AM,Y,11,03/03/2020 02:35:46 AM,...,79.0,36.0,303.0,16.0,8.0,N,N,N,N,chunk167.csv
51,200314692,2020-01-31 22:35:56,STATEP,2,STATEP,2,01/31/2020 10:36:21 PM,Y,25,01/31/2020 10:36:32 PM,...,114.0,26.0,401.0,30.0,12.0,N,N,N,N,chunk166.csv

In [20]:
## store rows 42 through 51 inclusive into a df called df_excerpt
df_excerpt=ems2020_excerpt_df.iloc[42:52]
df_excerpt

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
42,201542166,2020-06-02 14:39:16,CVAC,2,CVAC,2,06/02/2020 02:39:24 PM,Y,8,06/02/2020 02:39:43 PM,...,88.0,35.0,302.0,13.0,8.0,N,N,N,N,chunk171.csv
43,201290003,2020-05-08 00:02:09,EDP,7,EDP,7,05/08/2020 12:02:34 AM,Y,25,05/08/2020 12:02:55 AM,...,23.0,8.0,111.0,4.0,13.0,N,N,N,N,chunk170.csv
44,201034249,2020-04-12 21:17:40,SICK,6,SICK,6,04/12/2020 09:20:33 PM,Y,173,04/12/2020 09:20:33 PM,...,75.0,37.0,305.0,19.0,8.0,N,N,N,N,chunk169.csv
45,201784219,2020-06-26 22:59:45,INJURY,5,INJURY,5,06/26/2020 10:59:54 PM,Y,9,06/26/2020 11:00:01 PM,...,114.0,22.0,401.0,30.0,12.0,N,N,N,N,chunk172.csv
46,201001249,2020-04-09 08:29:26,INJURY,5,INJURY,5,04/09/2020 08:29:30 AM,Y,4,04/09/2020 08:29:55 AM,...,122.0,50.0,502.0,31.0,11.0,N,N,N,N,chunk169.csv
47,200880324,2020-03-28 01:22:22,SICK,6,SICK,6,03/28/2020 01:23:56 AM,Y,94,03/28/2020 01:24:07 AM,...,5.0,1.0,101.0,2.0,7.0,N,N,N,N,chunk168.csv
48,201323660,2020-05-11 23:40:32,UNC,2,UNC,2,05/11/2020 11:40:43 PM,Y,11,05/11/2020 11:40:48 PM,...,40.0,8.0,201.0,7.0,15.0,Y,N,N,N,chunk170.csv
49,201632450,2020-06-11 16:18:15,TRAUMA,2,TRAUMA,2,06/11/2020 04:18:34 PM,Y,19,06/11/2020 04:19:07 PM,...,67.0,40.0,317.0,17.0,9.0,N,N,N,N,chunk171.csv
50,200630307,2020-03-03 02:35:05,SICK,6,SICK,6,03/03/2020 02:35:16 AM,Y,11,03/03/2020 02:35:46 AM,...,79.0,36.0,303.0,16.0,8.0,N,N,N,N,chunk167.csv
51,200314692,2020-01-31 22:35:56,STATEP,2,STATEP,2,01/31/2020 10:36:21 PM,Y,25,01/31/2020 10:36:32 PM,...,114.0,26.0,401.0,30.0,12.0,N,N,N,N,chunk166.csv

In [21]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there

type(ems2020_excerpt_df)

pandas.core.frame.DataFrame

In [22]:
ems2020_excerpt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13117 entries, 0 to 13116
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   CAD_INCIDENT_ID                 13117 non-null  int64
 1   INCIDENT_DATETIME               13117 non-null  object
 2   INITIAL_CALL_TYPE               13117 non-null  object
 3   INITIAL_SEVERITY_LEVEL_CODE     13117 non-null  int64
 4   FINAL_CALL_TYPE                 13117 non-null  object
 5   FINAL_SEVERITY_LEVEL_CODE       13117 non-null  int64
 6   FIRST_ASSIGNMENT_DATETIME       13010 non-null  object
 7   VALID_DISPATCH_RSPNS_TIME_INDC  13117 non-null  object
 8   DISPATCH_RESPONSE_SECONDS_QY    13117 non-null  int64
 9   FIRST_ACTIVATION_DATETIME       12988 non-null  object
 10  FIRST_ON_SCENE_DATETIME         12533 non-null  object
 11  VALID_INCIDENT_RSPNS_TIME_INDC  13117 non-null  object
 12  INCIDENT_RESPONSE_SECONDS_QY    12533 non-null  float64
 13  INCIDENT_TRAVEL_TM_SECONDS_QY   12533 non-null  float64
 14  FIRST_TO_HOSP_DATETIME          7870 non-null   object
 15  FIRST_HOSP_ARRIVAL_DATETIME     7791 non-null   object
 16  INCIDENT_CLOSE_DATETIME         13110 non-null  object
 17  HELD_INDICATOR                  13117 non-null  object
 18  INCIDENT_DISPOSITION_CODE       12985 non-null  float64
 19  BOROUGH                         13117 non-null  object
 20  INCIDENT_DISPATCH_AREA          13117 non-null  object
 21  ZIPCODE                         12987 non-null  float64
 22  POLICEPRECINCT                  12988 non-null  float64
 23  CITYCOUNCILDISTRICT             12988 non-null  float64
 24  COMMUNITYDISTRICT               12988 non-null  float64
 25  COMMUNITYSCHOOLDISTRICT         12978 non-null  float64
 26  CONGRESSIONALDISTRICT           12988 non-null  float64
 27  REOPEN_INDICATOR                13117 non-null  object
 28  SPECIAL_EVENT_INDICATOR         13117 non-null  object
 29  STANDBY_INDICATOR               13117 non-null  object
 30  TRANSFER_INDICATOR              13117 non-null  object
 31  source                          13117 non-null  object
dtypes: float64(9), int64(4), object(19)
memory usage: 3.2+ MB

## Targeting an Excel sheet

We need the Customs and Border Protection data in this ```multi-data.xlsx``` workbook.

In [41]:
## import data here
import pandas as pd
pd

In [39]:
multidata=pd.read_excel("multi-data.xlsx")
multidata

,Serial Number,County,License Type Code,License Class Code,Certificate Number,Premise Name,DBA,Premise Address,Premise Address 2,Premise City,...,Premise Zip,License Issued Date,License Expiration Date,Method of Operation,Days/Hours of Operation,Other,Georeference,Zone,Effective Date,Original Date
0,2000777,ALBANY,HL,242,912771,SUPER HOST HOTELS INC,ALBANY RAMADA PLAZA,3 WATERVLIET AVE,NaN,ALBANY,...,12206,2019-11-15,2021-11-30,HOTEL RESTAURANT SERVING BEER WINE CIDER AND L...,NaN,NaN,POINT (-73.783705 42.674761),2,2019-12-01,1996-12-05
1,1197749,NASSAU,CT,246,913036,MEMORARE CATERERS INC,NaN,2183 JACKSON AVE A,WAVERLY AVE & MERRICK ROAD,SEAFORD,...,11783,2019-11-22,2021-11-30,CATERER SERVING BEER CIDER WINE AND LIQUOR,NaN,NaN,POINT (-73.487062 40.668214),1,2019-12-01,2007-12-18
2,2149537,SULLIVAN,AX,122,910149,AHMED TRADING INC,NaN,1302 STATE ROUTE 52,NaN,LOCH SHELDRAKE,...,12759,2018-11-19,2021-11-30,GROCERY SELLING BEER CIDER AND WINE PRODUCTS,NaN,NaN,POINT (-74.66699 41.777859),2,2018-12-01,2009-12-22
3,1311950,QUEENS,W,322,903719,CAOTICO LLC,FORET WINES,68-38 FOREST AVE,STOREFRONT C,RIDGEWOOD,...,11385,2018-12-31,2021-11-30,WINE STORE SELLING WINE,NaN,NaN,POINT (-73.90109 40.702673),1,2018-12-31,2018-12-31
4,2217319,PUTNAM,TW,344,917985,COFFEE TIME CAFE INC,NaN,559 RTE 6N,NaN,MAHOPAC,...,10541,2019-12-05,2021-11-30,TAVERN SERVING BEER AND WINE,NaN,NaN,POINT (-73.763883 41.374319),2,2019-12-05,2019-12-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50135,1311238,QUEENS,AX,122,847423,ZAHER MEAT CORP,REGO FRESH MARKETPLACE,63-76 WOODHAVEN BLVD,NaN,REGO PARK,...,11374,2021-07-07,2024-08-31,"GROCERY STORE SELLING BEER, WINE PRODUCTS AND ...",NaN,NaN,POINT (-73.86759 40.722457),1,2021-09-01,2018-09-12
50136,3002671,ERIE,AX,122,782775,WOODLAWN DELI INC,NaN,S 3306 LAKE SHORE ROAD,T/O WOODLAWN,BLASDELL,...,14219,2021-10-08,2024-10-31,GROCERY STORE SELLING BEER CIDER AND WINE PROD...,NaN,NaN,NaN,3,2021-11-01,1994-11-30
50137,2209433,ONONDAGA,AX,128,784064,7 ELEVEN INC,SUNOCO A PLUS #40215H,1000 W GENESEE ST,NaN,SYRACUSE,...,13204,2021-10-28,2024-10-31,GROCERY STORE SELLING BEER CIDER & WINE PRODUCTS,NaN,NaN,POINT (-76.17092 43.053662),2,2021-11-01,2018-02-01
50138,1312336,BRONX,CM,110,801200,TORCH & CROWN 704 BROADWAY LLC,TORCH & CROWN BREWING COMPANY,463 E 173RD ST,NaN,BRONX,...,10457,2021-11-08,2024-11-30,COMBINED CRAFT MANUFACTURER,Micro Brewer Serial #1312333,Farm Brewer Serial #1312335,POINT (-73.901384 40.841683),1,2021-12-01,2018-12-24
50139,2227379,ALBANY,WS,308,941478,DUSKY GOOSE LLC,DUSKY GOOSE,8355 NE WARREN RD,WWW.DUSKYGOOSE.COM,DUNDEE,...,97115,2021-10-06,2024-09-30,DIRECT WINE SHIPPER,NaN,NaN,POINT (-123.032311 45.276215),2,2021-10-06,2021-10-06

In [42]:
## call the top 15 rows

multidata.head(15)

,Serial Number,County,License Type Code,License Class Code,Certificate Number,Premise Name,DBA,Premise Address,Premise Address 2,Premise City,...,Premise Zip,License Issued Date,License Expiration Date,Method of Operation,Days/Hours of Operation,Other,Georeference,Zone,Effective Date,Original Date
0,2000777,ALBANY,HL,242,912771,SUPER HOST HOTELS INC,ALBANY RAMADA PLAZA,3 WATERVLIET AVE,NaN,ALBANY,...,12206,2019-11-15,2021-11-30,HOTEL RESTAURANT SERVING BEER WINE CIDER AND L...,NaN,NaN,POINT (-73.783705 42.674761),2,2019-12-01,1996-12-05
1,1197749,NASSAU,CT,246,913036,MEMORARE CATERERS INC,NaN,2183 JACKSON AVE A,WAVERLY AVE & MERRICK ROAD,SEAFORD,...,11783,2019-11-22,2021-11-30,CATERER SERVING BEER CIDER WINE AND LIQUOR,NaN,NaN,POINT (-73.487062 40.668214),1,2019-12-01,2007-12-18
2,2149537,SULLIVAN,AX,122,910149,AHMED TRADING INC,NaN,1302 STATE ROUTE 52,NaN,LOCH SHELDRAKE,...,12759,2018-11-19,2021-11-30,GROCERY SELLING BEER CIDER AND WINE PRODUCTS,NaN,NaN,POINT (-74.66699 41.777859),2,2018-12-01,2009-12-22
3,1311950,QUEENS,W,322,903719,CAOTICO LLC,FORET WINES,68-38 FOREST AVE,STOREFRONT C,RIDGEWOOD,...,11385,2018-12-31,2021-11-30,WINE STORE SELLING WINE,NaN,NaN,POINT (-73.90109 40.702673),1,2018-12-31,2018-12-31
4,2217319,PUTNAM,TW,344,917985,COFFEE TIME CAFE INC,NaN,559 RTE 6N,NaN,MAHOPAC,...,10541,2019-12-05,2021-11-30,TAVERN SERVING BEER AND WINE,NaN,NaN,POINT (-73.763883 41.374319),2,2019-12-05,2019-12-05
5,1319511,NEW YORK,RW,341,831035,DONATELLA MOXY 7TH AVENUE LLC,PROVA PIZZA BAR,485 7TH AVE,GROUND FLOOR,NEW YORK,...,10123,2019-12-23,2021-11-30,"RESTAURANT SERVING WINE, BEER AND CIDER",NaN,Recorded Music Permitted and No Dancing,NaN,1,2019-12-23,2019-12-23
6,2220767,MONTGOMERY,C,103,935317,CUDA BEVERAGE LLC,BILL'S BEVERAGE,1 WILLOW ST,NaN,AMSTERDAM,...,12010,2020-12-14,2021-11-30,WHOLESALE BEER,NaN,NaN,POINT (-74.1866 42.940987),2,2020-12-14,2020-12-14
7,2129283,ALBANY,WS,308,911084,"SILVERADO VINEYARDS, THE",NaN,6121 SILVERADO TRAIL,NaN,NAPA,...,94558,2018-12-03,2021-12-31,OUT OF STATE DIRECT SHIPPER,NaN,NaN,POINT (-122.33304899999999 38.40974),2,2019-01-01,2005-10-19
8,2138381,ALBANY,WS,308,911310,VOLCANO VINEYARDS LLC,VOLCANO WINERY,35 PILMAUNA DRIVE,NaN,VOLCANO,...,96785,2018-12-10,2021-12-31,OUT OF STATE DIRECT SHIPPER,NaN,NaN,NaN,2,2019-01-01,2007-06-28
9,2160505,ALBANY,WS,308,911278,J J COHN ESTATE LLC,NaN,5055 SOLANO AVE,7079689367,NAPA,...,94558,2018-12-10,2021-12-31,OUT OF STATE DIRECT WINE SHIPPER,NaN,NaN,POINT (-122.33301599999999 38.3548),2,2019-01-01,2010-07-02
10,2175892,ALBANY,WS,308,911215,KENEFICK RANCHES WINERY LLC,KENEFICK RANCH WINERY,4550 SILVERADO TRAIL,NaN,CALISTOGA,...,945159647,2018-12-07,2021-12-31,OUT OF STATE DIRECT SHIPPER,NaN,NaN,POINT (-122.54937700000002 38.57468),2,2019-01-01,2011-08-11
11,2188886,ALBANY,WS,308,909969,KSSM LLC,MICHAEL SCHLUMBERGER,4155 WINE CREEK RD,NaN,HEALDSBURG,...,95448,2018-11-08,2021-12-31,NaN,NaN,NaN,POINT (-122.95010999999998 38.656503),2,2019-01-01,2013-01-10
12,2192454,ALBANY,WS,308,918967,TERRAVANT WINE COMPANY LLC,TERRAVANT WINE COMPANY,35 & 70 INDUSTRIAL WAY,NaN,BUELLTON,...,93427,2019-06-17,2021-12-31,NaN,NaN,NaN,POINT (-120.202402 34.609092),2,2019-06-17,2013-08-30
13,1286881,NEW YORK,OP,252,913420,MERMAID 88 LLC,THE MERMAID INN,570-572 AMSTERDAM AVE,NaN,NEW YORK,...,10024,2019-12-05,2021-12-31,"RESTAURANT SERVING BEER, WINE, CIDER AND LIQUOR",RECORDED MUSIC. NO DANCING.,LICENSED SIDEWALK CAFE.,POINT (-73.97424 40.788753),1,2020-01-01,2015-09-15
14,1289791,BRONX,AX,122,912566,NEW FORDHAM FOOD PLAZA INC,NaN,2487 CRESTON AVE,NaN,BRONX,...,10468,2019-01-10,2021-12-31,GROCERY STORE SELLING BEER CIDER AND WINE PROD...,NaN,NaN,POINT (-73.898153 40.862681),1,2019-01-10,2016-01-28